### ISSUE TITLE
[Feature request] hex window IDs

### ISSUE THREAD

**Issue by prez** [neXromancers/shotgun#10]
It would be nice if window IDs in hexadecimal format could be supported, as that would allow simple oneliners like `shotgun -i $(xqp)` using [xqp](https://github.com/baskerville/xqp).

I also noticed the window IDs used by `xwininfo -int` / `shotgun` (if you convert them from dec) and `wmutils` / `xdo` / `xqp` don't match up.

Thank you.

**Comment by 9ary** [comment]
> It would be nice if window IDs in hexadecimal format could be supported, as that would allow simple oneliners like `shotgun -i $(xqp)` using [xqp](https://github.com/baskerville/xqp).

Sounds reasonable to me. I think the `0x` prefix should be enough to accept hex input?

> I also noticed the window IDs used by `xwininfo -int` / `shotgun` (if you convert them from dec) and `wmutils` / `xdo` / `xqp` don't match up.

It looks like this is because you are using a reparenting window manager (so am I, and I can reproduce this on i3). Some tools attempt to descend through the window tree, while others, including xqp, don't (understandably, since baskerville is the author of bspwm which is non-reparenting). [slop](https://github.com/naelstrof/slop/) lets you control that behavior with the `-n` flag.

**Comment by prez** [comment]
>Some tools attempt to descend through the window tree, while others, including xqp, don't 

That makes sense. Thank you so much!

**Comment by 9ary** [comment]
Keep in mind that as far as shotgun is concerned, both "types" of ID are valid, the only difference it will make is whether the decorations added by the window manager will be included in the screenshot or not.
