### ISSUE TITLE
Add --freeze option (like in scrot -f)

### ISSUE THREAD

**Issue by perdakovich** [neXromancers/shotgun#43]

**Comment by 9ary** [comment]
Thanks for the detailed issue. :)

This is out of scope for shotgun because it does not include a selection tool like scrot does. shotgun does not aim to be a drop-in replacement for scrot.
The recommended way to achieve this is to write your own script that would take a screenshot, display it in full-screen, and then start a selection tool like [hacksaw](https://github.com/neXromancers/hacksaw). You can then use the result to crop the image accordingly.

**Comment by tnjd** [comment]
alternatively (this is what I do) just open the full-screen screenshot in gimp to select / edit it

**Comment by perdakovich** [comment]
@expectocode 

> just open the full-screen screenshot in gimp

it would be slow then, and overall looks like a dirty hack

**Comment by tnjd** [comment]
@Goosegit11 for sure yep, it's a hack. But it works for occasional use. A full --freeze option is a lot of complexity and might deserve a full wrapper tool
